=== jacobcassidy/vscode-cassidy-dark-theme/dev/tooling/tokens/schemas/shared-semantic-definitions.schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "title": "Shared semantic definitions",
  "type": "object",
  "properties": {
    "standard": {
      "type": "array",
      "uniqueItems": true,
      "items": {
        "type": "string",
        "pattern": "^(?:\\*|[a-zA-Z][\\w-]*)(?:\\.[a-zA-Z][\\w-]*)*(?::[a-zA-Z][\\w+-]*)?$"
      }
    },
    "sourceCode": {
      "type": "array",
      "uniqueItems": true,
      "items": {
        "type": "string",
        "pattern": "^(?:\\*|[a-zA-Z][\\w-]*)(?:\\.[a-zA-Z][\\w-]*)*(?::[a-zA-Z][\\w+-]*)?$"
      }
    },
    "nonStandard": {
      "type": "array",
      "uniqueItems": true,
      "items": {
        "type": "string",
        "pattern": "^(?:\\*|[a-zA-Z][\\w-]*)(?:\\.[a-zA-Z][\\w-]*)*(?::[a-zA-Z][\\w+-]*)?$"
      }
    },
    "deprecated": {
      "type": "array",
      "uniqueItems": true,
      "items": {
        "type": "string",
        "pattern": "^(?:\\*|[a-zA-Z][\\w-]*)(?:\\.[a-zA-Z][\\w-]*)*(?::[a-zA-Z][\\w+-]*)?$"
      }
    }
  },
  "additionalProperties": false,
  "required": [
    "standard",
    "sourceCode",
    "nonStandard",
    "deprecated"
  ]
}

=== jacobcassidy/vscode-cassidy-dark-theme/dev/docs/references/tokens/previous-semantic-tokens.json
{
  "standard": [
    "*.abstract",
    "*.async",
    "*.declaration",
    "*.deprecated",
    "*.documentation",
    "*.modification",
    "*.readonly",
    "*.static",
    "class",
    "comment",
    "decorator",
    "enum",
    "enumMember",
    "event",
    "function",
    "function.defaultLibrary",
    "interface",
    "keyword",
    "macro",
    "method",
    "namespace",
    "number",
    "operator",
    "parameter",
    "property",
    "regexp",
    "string",
    "struct",
    "type",
    "typeParameter",
    "variable",
    "variable.abstract",
    "variable.async",
    "variable.declaration",
    "variable.defaultLibrary",
    "variable.definition",
    "variable.deprecated",
    "variable.documentation",
    "variable.modification",
    "variable.readonly",
    "variable.static"
  ],
  "sourceCode": [],
  "nonStandard": [
    "*.builtin",
    "*.callable",
    "*.classMember",
    "*.decorator",
    "*.escapeCharacter",
    "*.invalid",
    "*.keywordArgument",
    "*.library",
    "*.overridden",
    "*.typeHint",
    "*.typeHintComment",
    "arrow",
    "bracket",
    "builtinConstant",
    "clsParameter",
    "colon",
    "curlybrace",
    "intrinsic",
    "label",
    "magicFunction",
    "module",
    "parenthesis",
    "selfParameter",
    "semicolon",
    "defaultLibrary"
  ],
  "deprecated": []
}
